name: experimentation 

run-name: "Experimentation"

on: 
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: experimenting
        run: |
          echo $GREETING 
          echo $ADDITION 
          echo $EVENT 
        env:
          GREETING: ${{ 'hello'}} world
          ADDITION: ${{ 1 == 2}}
          EVENT : ${{github.event_name}}
      