name: My Practice github actions 1 

run-name: "This is run #${{ github.run_number }}"

on: 
  push : 
  workflow_dispatch:

jobs:
  build:
    runs-on : ubuntu-latest
    steps: 
      - name : my first step
        run: echo "hello world"