name: My Practice github actions 1 

run-name: "This is run #${{ github.run_number }}"


on: 
  push : 
    branches : ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on : ubuntu-latest
    steps: 
      - name: Experimenting
        uses: actions/checkout@v4
      - name: check the repo settings 
        run:  |
          ls -ltr
          echo "${{toJson(runner)}}"
          echo "${{toJson(env)}}"
          echo "${{toJson(secrets)}}"
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    if: ${{github.actor != 'test'}}
    steps: 
      -name: Die the person 
       run: | 
        echo "Result : ${{toJson(needs.build)}}"
