name: My Practice github actions 1 

run-name: "This is run #${{ github.run_number }}"

on: 
  push : 
    branches : ["main1"]
  workflow_dispatch:

jobs:
  build:
    runs-on : ubuntu-latest
    steps: 
      - name : my first step
        uses : actions/checkout@v4
      - name : check the repo settings 
        run :  |
          ls -ltr
          echo "${{toJson(runner)}}"