name: matrix

run-name : "This is run number "

on: 
  workflow_dispatch: 

jobs: 
  matrix_tests: 
    strategy: 
      version: ["0.1.0","0.1.1","0.2.0"]
      os: [ubuntu-latest,windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name : Run a multi liner script 
        run: | 
          echo "Running on ${{matrxi.os}} version ${{matrix.version}}"
